name: Add To GitHub projects

on:
  issues:
    types:
      - opened
      - labeled
      
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/fabiovinci/projects/6
          github-token: ${{ secrets.PROJECT_AUTOMATION }}
          labeled: question
          status: question
